export default function AnalystSummary({ summary }) {
  if (!summary) return null;
  const { headline, paragraphs = [], risks, strengths, watch_list } = summary;

  // §7 Analyze: AI Analyst Summary uses --ink-50 background, not --canvas.
  // The .analyst-card modifier applies that override on top of .card.
  return (
    <div className="card analyst-card">
      <h2 className="analyst-eyebrow">AI Analyst Summary</h2>
      <p className="analyst-headline">{headline}</p>

      {paragraphs.length > 0 && (
        <div className="analyst-paragraphs">
          {paragraphs.map((p, i) => (
            <p key={i} className="analyst-para">{p}</p>
          ))}
        </div>
      )}

      {risks.length > 0 && (
        <div className="analyst-section">
          <div className="analyst-section-title risk-title">Key Risks</div>
          <ul className="analyst-list">
            {risks.map((r, i) => (
              <li key={i} className="analyst-item risk-item">{r}</li>
            ))}
          </ul>
        </div>
      )}

      {strengths.length > 0 && (
        <div className="analyst-section">
          <div className="analyst-section-title strength-title">Strengths</div>
          <ul className="analyst-list">
            {strengths.map((s, i) => (
              <li key={i} className="analyst-item strength-item">{s}</li>
            ))}
          </ul>
        </div>
      )}

      {watch_list.length > 0 && (
        <div className="analyst-section">
          <div className="analyst-section-title watch-title">What to Monitor</div>
          <ul className="analyst-list">
            {watch_list.map((w, i) => (
              <li key={i} className="analyst-item watch-item">{w}</li>
            ))}
          </ul>
        </div>
      )}

      <p className="analyst-disclaimer">
        Generated by a deterministic rules engine from historical data.
        Not financial advice. Past performance does not predict future results.
      </p>
    </div>
  );
}
